<a href="https://colab.research.google.com/github/FredLali/FredLali/blob/main/Python_for_Researchers_Cohort_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Python

In [ ]:
print("Hello Researcher")

Hello Researcher

# Variables

In [ ]:
# Creating a variable
a = 3
height_m = 1.7
name_of_patient = "John Doe"
dayOfWeek = "Tuesday"

In [ ]:
print(name_of_patient)

John Doe

In [ ]:
# Doing some calculations
weight = 70
height = 1.7

bmi = weight / height ** 2
print(bmi)

24.221453287197235

In [ ]:
a = 15
b = 4

# Multiplication
a * b

60

In [ ]:
# Division
a / b

3.75

In [ ]:
# Addition
a + b

19

In [ ]:
# Subtraction
a - b

11

In [ ]:
# Modulo
a % b

3

In [ ]:
a // b

3

In [ ]:
# This is a comment
# This is a comment

In [ ]:
patient_age = 56

# Data Types

## int - used for whole number (both positive and negative)

In [ ]:
# Petient age
patient_age = 56

print(patient_age)

56

In [ ]:
# Check the type of data for patient_age
type(patient_age)

int

## float - decimal number

In [ ]:
# Height of patient
patient_height = 1.7
type(patient_height)

float

In [ ]:
# Height of patient
patient_height = 17.0
type(patient_height)

float

## Boolean - True or False

In [ ]:
# Illegibility
is_patient_ill = True
type(is_patient_ill)

bool

## String - text, comments, names, etc

In [ ]:
# String variables
name_of_patient = 'John Doe'
print(name_of_patient)
type(name_of_patient)

John Doe

str

In [ ]:
# String variables
name_of_guarantor = 'Sister's Husband'
print(name_of_guarantor)
type(name_of_guarantor)

SyntaxError: unterminated string literal (detected at line 2) (555367151.py, line 2)

In [ ]:
# String variables
name_of_guarantor = "Sister's Husband"
print(name_of_guarantor)
type(name_of_guarantor)

Sister's Husband

str

In [ ]:
# Multi-line string
comment = """
This lesson is brought to you by the CSU.
The Python class is taken by Gamah.
"""

print(comment)
type(comment)

This lesson is brought to you by the CSU.
The Python class is taken by Gamah.

str

In [ ]:
# Putting quotation mark around other variables
age_of_patient = "56"
is_eligible = True
print(is_eligible)
type(is_eligible)

True

bool

# Data Structures

## List

In [ ]:
# Modulo
8 % 5

3

In [ ]:
8 // 5

1

In [ ]:
# Creating a list
fruits = ["mango", "banana", "orange", "kiwi"]

print(fruits)
type(fruits)

['mango', 'banana', 'orange', 'kiwi']

list

In [ ]:
some_list = [23, "Jojo", True, 17.1]

print(some_list)
type(some_list)

[23, 'Jojo', True, 17.1]

list

In [ ]:
fruits = ["mango", "banana", "orange", "kiwi"]

In [ ]:
# Accessing a value in a list
fruits[1]

'banana'

In [ ]:
fruits[2]

'orange'

In [ ]:
fruits[-3]

'banana'

In [ ]:
fruits

['mango', 'banana', 'orange', 'kiwi']

In [ ]:
# Slicing
fruits[1:3]

['banana', 'orange']

In [ ]:
# Adding a value to a list - using append
fruits.append("pineapple")

print(fruits)

['mango', 'banana', 'orange', 'kiwi', 'pineapple']

In [ ]:
# Adding a value to a list - in a particular position
fruits.insert(2, "apple")

print(fruits)

['mango', 'banana', 'apple', 'orange', 'kiwi', 'pineapple']

In [ ]:
# Adding a value to a list - in a particular position
fruits.insert(2, "guava")
fruits.insert(2, "watermelon")
fruits.insert(2, "papaya")
fruits.insert(2, "grapes")


print(fruits)

['mango', 'banana', 'grapes', 'papaya', 'watermelon', 'guava', 'apple', 'orange', 'kiwi', 'pineapple']

In [ ]:
fruits

['mango',
 'banana',
 'grapes',
 'papaya',
 'watermelon',
 'guava',
 'apple',
 'orange',
 'kiwi',
 'pineapple']

In [ ]:
# Deleting a value from a list - using remove
fruits.remove("papaya")

print(fruits)

['mango', 'banana', 'grapes', 'watermelon', 'guava', 'apple', 'orange', 'kiwi', 'pineapple']

In [ ]:
# Deleting a value from a list - using pop
fruits.pop(2)

print(fruits)

['mango', 'banana', 'watermelon', 'guava', 'apple', 'orange', 'kiwi', 'pineapple']

## Dictionaries

In [ ]:
# Creating a dictionary
patient = {
    'name': "John Doe",
    'age': 56,
    'is_patient_ill': True,
    'weight': 75.5,
    'height': 1.75
}

print(patient)
type(patient)

{'name': 'John Doe', 'age': 56, 'is_patient_ill': True, 'weight': 75.5, 'height': 1.75}

dict

In [ ]:
patient

{'name': 'John Doe',
 'age': 56,
 'is_patient_ill': True,
 'weight': 75.5,
 'height': 1.75}

In [ ]:
# Accessing a value from a dictionary
patient["name"]

'John Doe'

In [ ]:
# Accessing a value from a dictionary
patient["names"]

KeyError: 'names'

In [ ]:
patient.get("age")

56

In [ ]:
# Adding new values to a dictionary
patient["is_diabetic"] = False

print(patient)

{'name': 'John Doe', 'age': 56, 'is_patient_ill': True, 'weight': 75.5, 'height': 1.75, 'is_diabetic': False}

In [ ]:
# Making changes to a value in a dictionary
patient["age"] = 65

print(patient)

{'name': 'John Doe', 'age': 65, 'is_patient_ill': True, 'weight': 75.5, 'height': 1.75, 'is_diabetic': False}

In [ ]:
# Deleting a value from a dictionary - using del
del patient["is_diabetic"]

print(patient)

{'name': 'John Doe', 'age': 65, 'is_patient_ill': True, 'weight': 75.5, 'height': 1.75}

In [ ]:
# Deleting a value from a dictionary - using pop
patient.pop("weight")

print(patient)

{'name': 'John Doe', 'age': 65, 'is_patient_ill': True, 'height': 1.75}

## Creating a dataframe from a dictionary

In [ ]:
patients_data = {
    "name": ["John Doe", "Jane Doe", "Elen Mike", "Jake Jack"],
    "age": [56, 61, 34, 40],
    "gender": ["Male", "Female", "Female", "Male"],
    "is_patient_ill": [True, False, True, True]
}

print(patients_data)
type(patients_data)

{'name': ['John Doe', 'Jane Doe', 'Elen Mike', 'Jake Jack'], 'age': [56, 61, 34, 40], 'gender': ['Male', 'Female', 'Female', 'Male'], 'is_patient_ill': [True, False, True, True]}

dict

In [ ]:
# Import pandas
import pandas as pd
df = pd.DataFrame(patients_data)

df

        name  age  gender  is_patient_ill
0   John Doe   56    Male            True
1   Jane Doe   61  Female           False
2  Elen Mike   34  Female            True
3  Jake Jack   40    Male            True

# Data Importation

In [ ]:
# Import the Pandas libary
import pandas as pd

## Reading Files from Google Drive

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/data/scores.csv")

data.head()

,number,days,gender,age,afftype,melanch,inpatient,edu,marriage,work,madrs1,madrs2
0,condition_1,11,2,35-39,2.0,2.0,2.0,6-10,1.0,2.0,19.0,19.0
1,condition_2,18,2,40-44,1.0,2.0,2.0,6-10,2.0,2.0,24.0,11.0
2,condition_3,13,1,45-49,2.0,2.0,2.0,6-10,2.0,2.0,24.0,25.0
3,condition_4,13,2,25-29,2.0,2.0,2.0,11-15,1.0,1.0,20.0,16.0
4,condition_5,13,2,50-54,2.0,2.0,2.0,11-15,2.0,2.0,26.0,26.0

# Reading Files from Our Working Environment

## Reading CSV Files

In [ ]:
# Reading CSV data
csv_data = pd.read_csv("/content/synthetic_data.csv")

csv_data.head()

    Country  Age  Gender Occupation   Income           Region
0  Zimbabwe   34  Female     Farmer  1734.67  Southern Africa
1     Kenya   23  Female     Doctor  1915.03      East Africa
2     Kenya   58    Male   Engineer  1450.26      East Africa
3  Tanzania   63  Female    Teacher  1824.95      East Africa
4      Mali   40  Female     Trader  1295.43      West Africa

### Reading a TSV file

In [ ]:
# Read a TSV data
tsv_data = pd.read_csv("/content/synthetic_data.tsv")

tsv_data.head()

    Country\tAge\tGender\tOccupation\tIncome\tRegion
0  Zimbabwe\t34\tFemale\tFarmer\t1734.67\tSouther...
1    Kenya\t23\tFemale\tDoctor\t1915.03\tEast Africa
2    Kenya\t58\tMale\tEngineer\t1450.26\tEast Africa
3  Tanzania\t63\tFemale\tTeacher\t1824.95\tEast A...
4     Mali\t40\tFemale\tTrader\t1295.43\tWest Africa

In [ ]:
# Read a TSV data
tsv_data = pd.read_csv("/content/synthetic_data.tsv", sep = "\t")

tsv_data.head()

    Country  Age  Gender Occupation   Income           Region
0  Zimbabwe   34  Female     Farmer  1734.67  Southern Africa
1     Kenya   23  Female     Doctor  1915.03      East Africa
2     Kenya   58    Male   Engineer  1450.26      East Africa
3  Tanzania   63  Female    Teacher  1824.95      East Africa
4      Mali   40  Female     Trader  1295.43      West Africa

### Reading TXT data

In [ ]:
txt_data = pd.read_csv("/content/synthetic_data.txt", sep = "\t")

txt_data.head()

    Country  Age  Gender Occupation   Income           Region
0  Zimbabwe   34  Female     Farmer  1734.67  Southern Africa
1     Kenya   23  Female     Doctor  1915.03      East Africa
2     Kenya   58    Male   Engineer  1450.26      East Africa
3  Tanzania   63  Female    Teacher  1824.95      East Africa
4      Mali   40  Female     Trader  1295.43      West Africa

### Reading Single Sheet Excel File

In [ ]:
excel_data = pd.read_excel("/content/synthetic_data.xlsx")

excel_data.head()

    Country  Age  Gender Occupation   Income           Region
0  Zimbabwe   34  Female     Farmer  1734.67  Southern Africa
1     Kenya   23  Female     Doctor  1915.03      East Africa
2     Kenya   58    Male   Engineer  1450.26      East Africa
3  Tanzania   63  Female    Teacher  1824.95      East Africa
4      Mali   40  Female     Trader  1295.43      West Africa

In [ ]:
# Checking the sheets in an Excel file
excel_file = pd.ExcelFile("/content/synthetic_data.xlsx")

excel_file.sheet_names

['Sheet1']

# Multiple Excel Sheet File

In [ ]:
multi_sheet = pd.ExcelFile("/content/synthetic_multisheet.xlsx")

multi_sheet.sheet_names

['Demographics', 'Income', 'Region']

In [ ]:
multi_sheet_data = pd.read_excel("/content/synthetic_multisheet.xlsx")

multi_sheet_data.head()

    Country  Age  Gender
0  Zimbabwe   34  Female
1     Kenya   23  Female
2     Kenya   58    Male
3  Tanzania   63  Female
4      Mali   40  Female

In [ ]:
# Read the Demographics sheet
demo_data = pd.read_excel("/content/synthetic_multisheet.xlsx", sheet_name = "Demographics")

demo_data.head()

    Country  Age  Gender
0  Zimbabwe   34  Female
1     Kenya   23  Female
2     Kenya   58    Male
3  Tanzania   63  Female
4      Mali   40  Female

In [ ]:
# Read the Income sheet
income_data = pd.read_excel("/content/synthetic_multisheet.xlsx", sheet_name = "Income")

income_data.head()

    Country Occupation   Income
0  Zimbabwe     Farmer  1734.67
1     Kenya     Doctor  1915.03
2     Kenya   Engineer  1450.26
3  Tanzania    Teacher  1824.95
4      Mali     Trader  1295.43

In [ ]:
# Read the Region sheet
region_data = pd.read_excel("/content/synthetic_multisheet.xlsx", sheet_name = "Region")

region_data.head()

    Country           Region
0  Zimbabwe  Southern Africa
1     Kenya      East Africa
2  Tanzania      East Africa
3      Mali      West Africa
4    Rwanda      East Africa

### Reading URL data

In [ ]:
df_url = pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/')

df_url.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [ ]:
cities = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv")

cities.head()

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State"""
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI

In [ ]:
snakes = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/snakes_count_10000.csv")

snakes.head()

   Game Number   "Game Length"
0            1              30
1            2              29
2            3              31
3            4              16
4            5              24